gluster_exporter/main.go, gluster_exporter/metric_brick.go
This change just calculates the individual brick utilization details
and doesnt do any aggregation based on volume types etc. The same
would be required at more abstract layer.
=> Added metrics for brick utilization

Makefile, scripts/gen-service.sh
`GLUSTER_MGMT` env variable can be used to control the systemd
unit file generation
To generate unit file to work with glusterd1
```
make
make install
```
To generate unit file to work with glusterd2
```
GLUSTER_MGMT=glusterd2 make
make install
```
=> systemd unit file

gluster-exporter/main.go
Earlier it was always set as localhost and doesnt work properly if explicitly
IP of the node is set in REST endpoint
=> Fixed to assign Glusterd2Endpoint in case gluster-mgmt value is glusterd2

gluster-exporter/main.go, gluster-exporter/metric_brick.go, gluster-exporter/metric_ps.go, gluster-exporter/metric_volume_counts.go, pkg/glusterutils/exporterd.go, pkg/glusterutils/gd1.go, pkg/glusterutils/peers_gd1.go, pkg/glusterutils/peers_gd2.go, pkg/glusterutils/types.go, pkg/glusterutils/volinfo_gd1.go, pkg/glusterutils/volinfo_gd2.go
added interface to run specific cmds against gd1 and gd2
gd1.go has gd1 related functions, gd2 has glusterd2 related functions
glusterutils.go has interface which gd1 and gd2 has to implement
Signed-off-by: venkata edara <redara@redhat.com>
=> gluster interface for gd1 and gd2

gluster-exporter/metric_volume_counts.go
Moved the IsLeader from init() to volumeCounts() in gluster-exporter/metric_volume_counts.go . The failure of an existing leader node will in turn lead to the other nodes not export metrics when the Isleader chick is in init().
=> Fix Leader Election Check

gluster-exporter/metric_brick.go
- gluster_brick_lv_size
- gluster_brick_lv_percent
- gluster_brick_lv_metadata_size
- gluster_brick_lv_metadata_percent
A snippet for metrics is as below
```
gluster_brick_lv_metadata_percent{brick_path="/root/gluster_bricks/vol1_b3",host="....",id="4252f846-eec5-4863-8b82-cf6ffc31c57a",instance="....:8080",job="prometheus",lv_path="/dev/centos_dhcp..../root",subvolume="vol1-replicate-0",vg_name="centos_dhcp....",volume="vol1"}	0
gluster_brick_lv_metadata_size{brick_path="/root/gluster_bricks/vol1_b3",host="....",id="4252f846-eec5-4863-8b82-cf6ffc31c57a",instance="....:8080",job="prometheus",lv_path="/dev/centos_dhcp..../root",subvolume="vol1-replicate-0",vg_name="centos_dhcp....",volume="vol1"}	0
gluster_brick_lv_percent{brick_path="/root/gluster_bricks/vol1_b3",host="....",id="4252f846-e …
```
=> Added LVM usage metrics

gluster-exporter/metric_volume.go, pkg/glusterutils/enable_profile_gd1.go, pkg/glusterutils/enable_profile_gd2.go, pkg/glusterutils/types.go
If `gluster_volume_profile` metrics collector is enabled and explicitly
for a volume the profiling is not disabled, it will enable profiling
for the volume so that profile specific metrics could be exposed.
Fixes: gluster/gluster-prometheus/issues/90
=> Added logic to enable profiling for volumes

docs/metrics.adoc, gluster-exporter/metric_volume.go, pkg/glusterutils/gd1.go, pkg/glusterutils/profileinfo_gd1.go, pkg/glusterutils/profileinfo_gd2.go, pkg/glusterutils/types.go
Added below metrics
- gluster_volume_profile_total_reads_interval
- gluster_volume_profile_total_writes_interval
- gluster_volume_profile_duration_secs_interval
- gluster_volume_profile_fop_hits_interval
- gluster_volume_profile_fop_avg_latency_interval
- gluster_volume_profile_fop_min_latency_interval
- gluster_volume_profile_fop_max_latency_interval
Fixes: gluster/gluster-prometheus/issues/101
=> Added interval stats metrics for volume profile info

gluster-exporter/metric_brick.go
This is required to uniquely identify the LVs for the bricks.
Fixes: gluster/gluster-prometheus/issues/114
=> Added LV UUID in labels for lvm metrics

pkg/glusterutils/profileinfo_gd2.go
A length field is added to 'make' functions.
This helps the append operation to starts from beginning of the array.
=> Fixing some minor issues in 'profileinfo_gd2.go' file

pkg/glusterutils/gd1.go
'port' field could contain 'N/A' as value, so changing the receiving
type (from int) to string
Fixes: gluster/gluster-prometheus/issues/109
=> Fixing XML parsing issue

docs/metrics.adoc
Generated metrics docs using the `make metrics-docgen` command
Fixes: Issue https://github.com/gluster/gluster-prometheus/issues/123
=> Adding the generated metrics docs

gluster-exporter/main.go, gluster-exporter/metric_brick.go, gluster-exporter/metric_peer_counts.go, gluster-exporter/metric_ps.go, gluster-exporter/metric_volume.go, gluster-exporter/metric_volume_counts.go
Changing the signature of the registering function,
from 'fn() error' to 'fn(glusterutils.GInterface) error'.
This helps (in future) to reduce a lot of global variables from passed
around.
Fixes: Issue https://github.com/gluster/gluster-prometheus/issues/100
=> Registering function signature change

extras/conf/gluster-exporter.toml.sample, gluster-exporter/conf/conf.go, gluster-exporter/main.go, pkg/glusterutils/cache.go, pkg/glusterutils/exporterd.go
'GInterface' (object's) methods can now cache the results within a TTL
(time-to-live) interval. By default caching is enabled for the methods,
but can be disabled through exporter-configuration file.
Fixes: #125
=> Adding caching mechanism to gluster-exporter

gluster-exporter/metric_brick.go, gluster-exporter/metric_peer_counts.go, gluster-exporter/metric_ps.go, gluster-exporter/metric_volume.go, gluster-exporter/metric_volume_counts.go, gluster-exporter/metrics.go
Ref #89 
Using const metrics ensures values for old labels (such as for deleted volumes) are not reported again
=> Forget old volumes

extras/conf/gluster-exporter.toml.sample, gluster-exporter/conf/conf.go, gluster-exporter/main.go, gluster-exporter/metric_brick.go, gluster-exporter/metric_volume.go, gluster-exporter/metric_volume_counts.go, pkg/glusterutils/cache.go, pkg/glusterutils/common.go, pkg/glusterutils/enable_profile_gd1.go, pkg/glusterutils/enable_profile_gd2.go, pkg/glusterutils/exporterd.go, pkg/glusterutils/gd1.go, pkg/glusterutils/glusterconsts/consts.go, pkg/glusterutils/types.go, pkg/glusterutils/volinfo_gd1.go
There are TWO kinds of configs here,
1. ```conf.Config```, exporter TOML configuration
2. ```glusterutils.Config```, gluster configuration
**Config creation**
* Creating ```conf.Config```
Following function will create it,
```conf.LoadConfig(toml_file_path)```
* Creating ```glusterutils.Config```
This config can be created from ```conf.Config``` object,
```glusterutils.GConfigFromExporterConfig(*conf.Config)```
**Accessing the configuration**
* Getting ```conf.Config``` object
We retrieve the exporter config through ```glusterutils.Config``` object
```gConfig.ParentConfig()``` returns ```conf.Config```
* Getting ```glusterutils.Config``` object
This config is got from GD1 or GD2 objects,
```GD1_or_GD2_object.Config()```
* But as we are passing it (GD1/GD2 objects) as ```GInterface``` …
=> Standardizing Gluster configuration handling

gluster-exporter/main.go, gluster-exporter/metric_brick.go, gluster-exporter/metric_peer_counts.go, gluster-exporter/metric_ps.go, gluster-exporter/metric_volume.go, gluster-exporter/metric_volume_counts.go
All the logs which could happen on every execution of collectors
due to volume, bricks and other calls, now changed to Debug. This
is required to make sure /var/log doesnt get hogged due to gluster
exporter just because there are some problematic volume, bricks etc.
Fixes: gluster/gluster-prometheus/issues/126
=> Changed the log severity to Debug

gluster-exporter/conf/conf.go, gluster-exporter/metric_volume.go, scripts/install-reqs.sh
New errors catched after upgrading to gometalinter v3.0.0
gluster-exporter/conf/conf.go:104:24:warning: error strings should not
be capitalized (ST1005) (staticcheck)
gluster-exporter/metric_volume.go:252:25:warning: error strings should
not be capitalized (ST1005) (staticcheck)
gluster-exporter/metric_volume.go:254:25:warning: error strings should
not be capitalized (ST1005) (staticcheck)
=> Fix gometalinter issues

gluster-exporter/metric_peers.go, pkg/glusterutils/peers_gd1.go, pkg/glusterutils/peers_gd2.go, pkg/glusterutils/types.go
Our use case for `gluster-prometheus` is to monitor the health of our deployed GlusterD1 clusters. Since we're planning to deploy `gluster-prometheus` on OpenShift in pods separate from the `glusterfs-storage` pods, we plan to extract all the data that we require for metrics by using the `--remote-host` flag to connect to the GlusterD1 instances.
Therefore we need metrics that can tell us about the health of the cluster. Since we've seen cases in the past where peers would get stuck in odd states, we want to monitor `peer.state` which was not exposed by `Peer` in `pkg/glusterutils`.
This merge request exposes `peer.state` when the exporter is running with the GD1 backend, and sets the value of `peer.state` to `-1` when running with the GD2 backend.
On top of this, we implement a new …
=> Implement metrics which provide information about peers

gluster-exporter/metric_volume_status.go, pkg/glusterutils/brick_status_gd1.go, pkg/glusterutils/cache.go, pkg/glusterutils/gd1.go, pkg/glusterutils/types.go, pkg/glusterutils/volstatus_gd1.go, pkg/glusterutils/volstatus_gd2.go
We currently monitor various brick metrics in our GlusterD1 deployments. These metrics are based on the output of `gluster --mode=script --xml volume status all detail` and we would like to have these metrics available from `gluster-prometheus`.
This merge request implements a new back end method `VolumeStatus` which produces a list of all the volumes in the cluster, where each record in the list contains a `BrickStatus` record for each brick of the volume.
The new metrics module then provides a number of metrics that we will use to implement alerts such as volumes running out of space or inodes, or volumes with offline bricks.
=> Brick-level metrics for all volumes in a cluster

README.adoc, extras/conf/gluster-exporter.toml.sample, pkg/glusterutils/common.go, pkg/glusterutils/gd1.go
Instead of using `gd1-remote-host = "localhost"`, I've disabled the default value.
In the gd1 client, the `--remote-host` parameter is only used set if GlusterRemoteHost is set.
That way :
* the (I assume) basic use case of running the exporter on a glusterd node works fine without a `gd1-remote-host`
* using a remote-host is still possible
I've also added a few comments to highlight the using a `gd1-remote-host` will prevent from using `gluster_volume_counts` and `gluster_volume_profile`.
Fixes #151
=> Gd1 optional remote host

gluster-exporter/metric_brick.go, gluster-exporter/metric_peer_counts.go, gluster-exporter/metric_peers.go, gluster-exporter/metric_ps.go, gluster-exporter/metric_volume.go, gluster-exporter/metric_volume_counts.go, gluster-exporter/metric_volume_status.go, gluster-exporter/metrics.go
Reseting all metrics causes missing entries since the Prometheus
server may pull the metrics from exporter when it was reset.
To avoid the problem, TTL option is provided(Default is 2 minutes).
If a Metric is not exported for the TTL period, then it deletes
that metric from exporter to avoid stale entries.
Fixes: #158
=> Added TTL to all Metrics exported

Makefile, extras/debian.Dockerfile
1. optimize container image size.  
2. make dep ensuer retry until success, useful for some poor network circumstance.
=> optimize image size
