gluster/gluster-prometheus

- gluster_exporter/metric_brick.go
> Added brick effective utilization for subvolumes

- gluster_exporter/main.go
- gluster_exporter/metric_brick.go
- gluster_exporter/metric_ps.go
> Replaced nodeid with peerid

- README.adoc
> Added build status in README

- extras/conf/gluster-exporter.toml.sample
- gluster-exporter/metric_volume_counts.go
- total no of volumes
- started no of volumes
- stopped no of volumes
- bricks count for volumes
> Added metrics for volume counters

- Gopkg.lock
- Gopkg.toml
- pkg/logging/logger.go
To use this utility, initialize the logger as below first
```
import (
"github.com/gluster/gluster-prometheus/pkg/logging"
log "github.com/sirupsen/logrus"
)
if err := logging.Init({sample-log-dir}, {sample-log-file}, {sample-log-level}); err != nil {
log.WithError(err).Fatal("Failed to initialize logging")
}
```
After initialize done for logging the message use below code
```
log.WithError({err-object}).Fatal("{error-message}")
```
> Added logger for project

- gluster-exporter/metric_brick.go
- gluster-exporter/metric_volume_counts.go
- pkg/glusterutils/types.go
> Export brick metrics only if Volume is in Started state

- Gopkg.lock
- Gopkg.toml
> use released version of toml pkg instead of master

- gluster-exporter/metric_volume_counts.go
- pkg/logging/logger.go
- scripts/gometalinter-tests.sh
Also fixed the errors reported by `gometalinter` again
> fix issue with gometalinter return code

- pkg/glusterutils/gd1.go
- pkg/glusterutils/healinfo_gd1.go
- pkg/glusterutils/healinfo_gd2.go
- pkg/glusterutils/types.go
added healinfo_gd1.go and healinfo_gd2.go to handle
respective heal info
Signed-off-by: venkata edara <redara@redhat.com>
> Added HealInfo for gd1 and gd2

- extras/nightly-rpms.sh
- extras/rpms/gluster-prometheus-exporter.spec
> Fix version replacement issue

- Makefile
- README.adoc
- docs/metrics.adoc
- gluster-exporter/docgen.go
- gluster-exporter/main.go
- gluster-exporter/metric_brick.go
- gluster-exporter/metric_ps.go
- gluster-exporter/metric_volume_counts.go
- gluster-exporter/metrics.go
`docs/metrics.adoc` file is generated using the metrics information
available `docs/metrics.yml` by running `make metrics-docgen`.
> Documenting the supported metrics.

- rules/volume-utilization.yml
> Prometheus rule to get Volume utilization

- gluster-exporter/main.go
> Create Log directory if not exists

- docs/metrics.adoc
- gluster-exporter/docgen.go
- rules/volume-utilization.yml
Also generated missing doc for new metrics
> Namespace prefix added to all exposed metrics

- docs/metrics.adoc
- extras/conf/gluster-exporter.toml.sample
- gluster-exporter/metric_volume.go
Signed-off-by: venkata edara <redara@redhat.com>
> Added Self Heal exporter

- gluster-exporter/metric_volume_counts.go
- pkg/glusterutils/gd1.go
- pkg/glusterutils/snapshots_gd1.go
- pkg/glusterutils/snapshots_gd2.go
- pkg/glusterutils/types.go
- gluster_volume_snapshot_brick_count_total
- gluster_volume_snapshot_brick_count_active
Fixes: gluster/gluster-prometheus/issues/70
> Added volume snapshot bricks count metrics

- gluster-exporter/metric_brick.go
Fixes: gluster/gluster-prometheus/issues/92
> Added metric gluster_subvol_capacity_total_bytes

- Gopkg.lock
- docs/metrics.adoc
- extras/conf/gluster-exporter.toml.sample
- gluster-exporter/metric_volume.go
- pkg/glusterutils/gd1.go
- pkg/glusterutils/healinfo_gd1.go
- pkg/glusterutils/profileinfo_gd1.go
- pkg/glusterutils/profileinfo_gd2.go
- pkg/glusterutils/types.go
- gluster_volume_profile_total_reads
- gluster_volume_profile_total_writes
- gluster_volume_profile_duration_secs
Fixes: gluster/gluster-prometheus/issues/55
> Added volume profile related metrics

- docs/metrics.adoc
- gluster-exporter/metric_peer_counts.go
- pkg/glusterutils/exporterd.go
- pkg/glusterutils/healinfo_gd1.go
> Added pvs, lvs, vgs count metrics

- extras/conf/gluster-exporter.toml.sample
- gluster-exporter/metric_brick.go
- gluster-exporter/metric_volume_counts.go
- pkg/glusterutils/brick_status_gd1.go
- pkg/glusterutils/brick_status_gd2.go
- pkg/glusterutils/gd1.go
- pkg/glusterutils/types.go
Added metrics
- gluster_brick_up
- gluster_volume_up
Fixes: gluster/gluster-prometheus/issues/84
> Added volume and brick status metrics

- gluster-exporter/metric_brick.go
Fixes: gluster/gluster-prometheus/issues/115
> Added volume name in lables for thinpool related metrics

- gluster-exporter/metric_peer_counts.go
Corrected the logic to count the thinpools
fixes: https://github.com/gluster/gluster-prometheus/issues/111
> Corrected the 'thinpool_count' metrics

- gluster-exporter/metric_volume.go
Aggregated operations like READ_WRITE_OPS, LOCK_OPS, INODE_OPS and
ENTRY_OPS are added to the metrics
Fixes:  gluster/gluster-prometheus/issues/98
> Adding the aggregated operations.

- gluster-exporter/metric_brick.go
Fixes: gluster/gluster-prometheus/issues/121
> Fixed issue while getting LV metrics for bricks

- gluster-exporter/metric_volume_counts.go
> Fix error reporting on non-leader in volume counts

- gluster-exporter/metric_volume_counts.go
> Fix volume_count inconsistent label cardinality

- gluster-exporter/main.go
> Don't create logDir if logging to stderr/stdout

- pkg/glusterutils/exporterd.go
> Fix leader election logic for GD2

- pkg/glusterutils/volinfo_gd1.go
> Fix wrong brick index while parsing Volume info

- README.adoc
- extras/conf/gluster-exporter.toml.sample
> Change default port to 9713

- README.adoc
Hi, 
just some minor additions to the README. 
- Added hint about requirements installations
- See also https://github.com/gluster/gluster-prometheus/issues/56
> Extend README
